# Generated by Django 5.0.1 on 2024-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina_licencia',
            name='run',
            field=models.CharField(max_length=12),
        ),
    ]
