# Generated by Django 5.0.1 on 2024-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitar', '0002_alter_nomina_licencia_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina_licencia',
            name='folio',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
